/* ------------------------------------------------------ */
/*                         Import                         */
/* ------------------------------------------------------ */
/* ---------------------- external ---------------------- */
const mongoose = require('mongoose');

/* ------------------------------------------------------ */
/*                         Schema                         */
/* ------------------------------------------------------ */
const pokemonSchema = mongoose.Schema(
  {
    order: {
      type: Number,
      unique: true,
      required: [true, 'Please provide an order number']
    },
    name: {
      type: String,
      unique: true,
      required: [true, 'Please provide a name']
    },
    imageURL: {
      type: String,
      unique: true,
      required: [true, 'Please provide an image']
    },
    height: {
      type: Number,
      required: [true, 'Please specify a height']
    },
    weight: {
      type: Number,
      required: [true, 'Please specify a weight']
    },
    types: [
      {
        type: String,
        enum: [
          'bug',
          'dark',
          'dragon',
          'electric',
          'fairy',
          'fighting',
          'fire',
          'flying',
          'ghost',
          'grass',
          'ground',
          'ice',
          'normal',
          'poison',
          'psychic',
          'rock',
          'steel',
          'water'
        ],
        required: [true, 'Please specify at least one type']
      }
    ],
    abilities: [
      {
        type: String,
        enum: [
          'adaptability',
          'aerilate',
          'aftermath',
          'air-lock',
          'analytic',
          'anger-point',
          'anticipation',
          'arena-trap',
          'aroma-veil',
          'aura-break',
          'bad-dreams',
          'ball-fetch',
          'battery',
          'battle-armor',
          'battle-bond',
          'beast-boost',
          'berserk',
          'big-pecks',
          'blaze',
          'bulletproof',
          'cheek-pouch',
          'chlorophyll',
          'clear-body',
          'cloud-nine',
          'color-change',
          'comatose',
          'competitive',
          'compound-eyes',
          'contrary',
          'corrosion',
          'cotton-down',
          'cursed-body',
          'cute-charm',
          'damp',
          'dancer',
          'dark-aura',
          'dauntless-shield',
          'dazzling',
          'defeatist',
          'defiant',
          'delta-stream',
          'desolate-land',
          'disguise',
          'download',
          'drizzle',
          'drought',
          'dry-skin',
          'early-bird',
          'effect-spore',
          'electric-surge',
          'emergency-exit',
          'fairy-aura',
          'filter',
          'flame-body',
          'flare-boost',
          'flash-fire',
          'flower-gift',
          'flower-veil',
          'fluffy',
          'forecast',
          'forewarn',
          'friend-guard',
          'frisk',
          'full-metal-body',
          'fur-coat',
          'gale-wings',
          'galvanize',
          'gluttony',
          'gooey',
          'gorilla-tactics',
          'grass-pelt',
          'grassy-surge',
          'gulp-missile',
          'guts',
          'harvest',
          'healer',
          'heatproof',
          'heavy-metal',
          'honey-gather',
          'huge-power',
          'hunger-switch',
          'hustle',
          'hydration',
          'hyper-cutter',
          'ice-body',
          'ice-face',
          'ice-scales',
          'illuminate',
          'illusion',
          'immunity',
          'imposter',
          'infiltrator',
          'innards-out',
          'inner-focus',
          'infiltrator',
          'insomnia',
          'intimidate',
          'intrepid-sword',
          'iron-barbs',
          'iron-fist',
          'iron-fist',
          'justified',
          'keen-eye',
          'klutz',
          'leaf-guard',
          'levitate',
          'libero',
          'light-metal',
          'lightning-rod',
          'limber',
          'liquid-ooze',
          'liquid-voice',
          'long-reach',
          'magic-bounce',
          'magic-guard',
          'magician',
          'magma-armor',
          'magnet-pull',
          'marvel-scale',
          'mega-launcher',
          'merciless',
          'mimicry',
          'minus',
          'mirror-armor',
          'misty-surge',
          'mold-breaker',
          'moody',
          'motor-drive',
          'moxie',
          'multiscale',
          'multitype',
          'mummy',
          'natural-cure',
          'neuroforce',
          'neutralizing-gas',
          'no-guard',
          'normalize',
          'oblivious',
          'overcoat',
          'overgrow',
          'own-tempo',
          'parental-bond',
          'pastel-veil',
          'perish-body',
          'pickpocket',
          'pickup',
          'pixilate',
          'plus',
          'poison-heal',
          'poison-point',
          'poison-touch',
          'power-construct',
          'power-of-alchemy',
          'power-spot',
          'prankster',
          'pressure',
          'primordial-sea',
          'prism-armor',
          'propeller-tail',
          'protean',
          'psychic-surge',
          'punk-rock',
          'pure-power',
          'queenly-majesty',
          'quick-feet',
          'rain-dish',
          'rattled',
          'receiver',
          'reckless',
          'refrigerate',
          'regenerator',
          'ripen',
          'rivalry',
          'rks-system',
          'rock-head',
          'rough-skin',
          'run-away',
          'sand-force',
          'sand-rush',
          'sand-spit',
          'sand-stream',
          'sand-veil',
          'sap-sipper',
          'schooling',
          'scrappy',
          'screen-cleaner',
          'serene-grace',
          'shadow-shield',
          'shadow-tag',
          'shed-skin',
          'sheer-force',
          'shell-armor',
          'shield-dust',
          'shields-down',
          'simple',
          'skill-link',
          'slow-start',
          'slush-rush',
          'sniper',
          'snow-cloak',
          'snow-warning',
          'solar-power',
          'solid-rock',
          'soul-heart',
          'soundproof',
          'speed-boost',
          'stakeout',
          'stall',
          'stalwart',
          'stamina',
          'stance-change',
          'static',
          'steadfast',
          'steam-engine',
          'steelworker',
          'steel-spirit',
          'stench',
          'sticky-hold',
          'strong-jaw',
          'storm-drain',
          'storm-jaw',
          'sturdy',
          'suction-cups',
          'super-luck',
          'surge-surfer',
          'swarm',
          'sweet-veil',
          'swift-swim',
          'symbiosis',
          'synchronize',
          'tangled-feet',
          'tangling-hair',
          'technician',
          'telepathy',
          'teravolt',
          'thick-fat',
          'tinted-lens',
          'torrent',
          'tough-claws',
          'toxic-boost',
          'trace',
          'triage',
          'truant',
          'turboblaze',
          'unaware',
          'unburden',
          'unnerve',
          'victory-star',
          'vital-spirit',
          'volt-absorb',
          'wandering-spirit',
          'water-absorb',
          'water-bubble',
          'water-compaction',
          'water-veil',
          'weak-armor',
          'white-smoke',
          'wimp-out',
          'wonder-guard',
          'wonder-skin',
          'zen-mode'
        ],
        required: [true, 'Please specify at least one ability']
      }
    ],
    stats: {
      attack: {
        type: Number,
        min: [0, 'Stat must be above 0']
      },
      defense: {
        type: Number,
        min: [0, 'Stat must be above 0']
      },
      hp: {
        type: Number,
        min: [0, 'Stat must be above 0']
      },
      speed: {
        type: Number,
        min: [0, 'Stat must be above 0']
      },
      specialDefense: {
        type: Number,
        min: [0, 'Stat must be above 0']
      },
      specialAttack: {
        type: Number,
        min: [0, 'Stat must be above 0']
      }
    },
    createdAt: {
      type: Date,
      default: Date.now,
      select: false
    }
  },
  {
    versionKey: false
  }
);

/* ------------------------------------------------------ */
/*                         Export                         */
/* ------------------------------------------------------ */
const Pokemon = mongoose.model('Pokemon', pokemonSchema);
module.exports = Pokemon;
